check-location: # коардинаты и мир телепортации
  world: world
  x: 0
  y: 70
  z: 0
  yaw: 0
  pitch: 0

formats:
  checker-format: "&e[ &bПроверяющий &e] &r%vault_prefix% &f%player_name% &f>> &f%message%"
  target-format: "&e[ &bИгрок &e] &r%vault_prefix% &f%player_name% &f>> &f%message%"

sounds:
  check-start: # звук в начале проверки
    sound: "ENTITY_RAVAGER_DEATH"
    volume: 1.0
    pitch: 1.0
  check-end: # Звук в конце проверки
    sound: "ENTITY_PLAYER_LEVELUP"
    volume: 1.0
    pitch: 1.0

messages:
  reload-success: "&aУспешная перезагрузка"
  no-permission: "&cУ вас нет прав на эту команду!"
  only-players: "&cТолько игроки могут использовать эту команду!"
  check-usage: "&eИспользование: /check <ник> [clear]"
  player-not-found: "&cИгрок не найден!"
  check-started: "&aВы начали проверку игрока %player%"
  check-complete: "&aПроверка завершена!"
  player-cleared: "&aВы свободный. Удачной игры!"
  cannot-check-self: "&cВы не можете проверить самого себя!"
  cannot-check-staff: "&cВы не можете проверить этого игрока!"
  instructions:
    - "&6╔ &fПроверка на читы!"
    - "&6╚ &fПишите свой &1&lDiscord &fили код &c&lAnyDesk"

titles:
  target-notification:
    title: "&cПроверка на читы"
    subtitle: ""
    fadeIn: 5
    stay: 150
    fadeOut: 5
  player-cleared:
    title: "&aПроверка пройдена"
    subtitle: "&fУдачной игры"
    fadeIn: 5
    stay: 40
    fadeOut: 10

settings:
  auto-end-delay: 86400 # Автомотическое завершение проверки через 1 день
  restrict-movement: true # вкл/выкл возможность движения. default: true
  use-placeholderapi: true
  update-checker: true
  update-notify: true